sudo: required
services:
  - docker

before_install:
  - docker build -t zsheill/docker-react -f Dockerfile.dev .

script:
  - docker run zsheill/docker-react npm run test -- --coverage

# language: generic
#
deploy:
  provider: elasticbeanstalk
  # region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-373404038041",
  # bucket_path: "docker-react"
  # on:
  #   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
